### ISSUE TITLE
GetPresignedURL name参数被urlencode后导致的无法正常访问

### ISSUE THREAD

**Issue by virskor** [tencentyun/cos-go-sdk-v5#110]
![image](https://user-images.githubusercontent.com/16968535/110424474-d5eae180-80dd-11eb-8a80-c266b973f07e.png)

调用 filePreSignedURL, err := GetClient().Object.GetPresignedURL(context.Background(), http.MethodGet, name, secretID, secretKey, time.Hour, nil)

name 值为 name /public/avatar/000/00/00/01.png

**Comment by virskor** [comment]
暂用 filePreSignedURL.RawQuery 拼接，是否考虑增加直接获取签名的方法

**Comment by agin719** [comment]
name不需要包括最前面的 / 符号

**Comment by virskor** [comment]
http://dehong-ren-production-1257658779.cos.ap-beijing.myqcloud.com/public/avatar/000/00/00/01.png?q-sign-algorithm=sha1&q-ak=AKIDPholhSSdx670jCwlqqgmhRI4hBTgqdQo&q-sign-time=1615273226%3B1615276826&q-key-time=1615273226%3B1615276826&q-header-list=host&q-url-param-list=&q-signature=b71c0898340ed7314f566eb4b290f0695e6d5356   生成的签名 q-sign-time 和 q-key-time 似乎有问题 传入的expires 是  time.Hour

**Comment by agin719** [comment]
filePreSignedURL, err := GetClient().Object.GetPresignedURL(context.Background(), http.MethodGet, name, secretID, secretKey, time.Hour, nil)
直接把filePreSignedURL打印出来访问呢，并把filePreSignedURL贴出来。注意name不需要包含最前面的/。

**Comment by virskor** [comment]
name = ""

打印的结果 https://dehong-ren-production-1257658779.cos.ap-beijing.myqcloud.com/?q-sign-algorithm=sha1&q-ak=AKIDPholhSSdx670jCwlqqgmhRI4hBTgqdQo&q-sign-time=1615274003%3B1615277603&q-key-time=1615274003%3B1615277603&q-header-list=host&q-url-param-list=&q-signature=90df5bd7fb7cdd1cda0ffb1ddc368bab5695c347

**Comment by virskor** [comment]
name = "public/avatar/000/00/00/01.png"

https://dehong-ren-production-1257658779.file.myqcloud.compublic/avatar/000/00/00/01.png?q-sign-algorithm=sha1&q-ak=AKIDPholhSSdx670jCwlqqgmhRI4hBTgqdQo&q-sign-time=1615274050%3B1615277650&q-key-time=1615274050%3B1615277650&q-header-list=host&q-url-param-list=&q-signature=85bd0f8f5ecb6243f6488fae77b778c36760b772

**Comment by virskor** [comment]
name = "public/avatar/000/00/00/01.png"

https://dehong-ren-production-1257658779.file.myqcloud.compublic%2favatar%2f000%2f00%2f00%2f01.png?q-sign-algorithm=sha1&q-ak=AKIDPholhSSdx670jCwlqqgmhRI4hBTgqdQo&q-sign-time=1615274050%3B1615277650&q-key-time=1615274050%3B1615277650&q-header-list=host&q-url-param-list=&q-signature=85bd0f8f5ecb6243f6488fae77b778c36760b772

**Comment by agin719** [comment]
https://github.com/tencentyun/cos-go-sdk-v5/blob/master/example/object/getByPresignedURL.go

**Comment by agin719** [comment]
https://github.com/tencentyun/cos-go-sdk-v5/blob/master/example/object/getByPresignedURL.go  请参考下这里，filePreSignedURL结果是做过处理吗，域名后面少了/ ， 还有你的域名是cdn域名，鉴权方式不一样的，具体咨询可以直接在腾讯云上提工单哈，谢谢。

**Comment by virskor** [comment]
我用demo 跑的

打印的结果是 https://dehong-ren-production-1257658779.cos.ap-beijing.myqcloud.com/public%2Favatar%2F000%2F00%2F00%2F01.png?q-sign-algorithm=sha1&q-ak=&q-sign-time=1615276990%3B1615280590&q-key-time=1615276990%3B1615280590&q-header-list=host&q-url-param-list=&q-signature=5e8bcfc5239f7a596fbad3733e7d80372710a6e1%     


是无法访问的
以下是代码

```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"time"

	"github.com/tencentyun/cos-go-sdk-v5"
	"github.com/tencentyun/cos-go-sdk-v5/debug"
)

func log_status(err error) {
	if err == nil {
		return
	}
	if cos.IsNotFoundError(err) {
		// WARN
		fmt.Println("WARN: Resource is not existed")
	} else if e, ok := cos.IsCOSError(err); ok {
		fmt.Printf("ERROR: Code: %v\n", e.Code)
		fmt.Printf("ERROR: Message: %v\n", e.Message)
		fmt.Printf("ERROR: Resource: %v\n", e.Resource)
		fmt.Printf("ERROR: RequestId: %v\n", e.RequestID)
		// ERROR
	} else {
		fmt.Printf("ERROR: %v\n", err)
		// ERROR
	}
}

func main() {
	ak := os.Getenv("")
	sk := os.Getenv("")
	u, _ := url.Parse("https://dehong-ren-production-1257658779.cos.ap-beijing.myqcloud.com")
	b := &cos.BaseURL{BucketURL: u}
	c := cos.NewClient(b, &http.Client{
		Transport: &cos.AuthorizationTransport{
			SecretID:  ak,
			SecretKey: sk,
			Expire:    time.Hour,
			Transport: &debug.DebugRequestTransport{
				RequestHeader:  true,
				RequestBody:    true,
				ResponseHeader: true,
				ResponseBody:   true,
			},
		},
	})

	name := "public/avatar/000/00/00/01.png"
	ctx := context.Background()

	// Normal header way to get object
	// resp, err := c.Object.Get(ctx, name, nil)
	// log_status(err)
	// bs, _ := ioutil.ReadAll(resp.Body)
	// resp.Body.Close()

	// Get presigned
	presignedURL, err := c.Object.GetPresignedURL(ctx, http.MethodGet, name, ak, sk, time.Hour, nil)
	log_status(err)
	print(presignedURL.String())

	// // Get object by presinged url
	// resp2, err := http.Get(presignedURL.String())
	// log_status(err)
	// bs2, _ := ioutil.ReadAll(resp2.Body)
	// resp2.Body.Close()
	// fmt.Printf("result2 is : %s\n", string(bs2))

	// fmt.Printf("%v\n\n", bytes.Compare(bs2, bs) == 0)

}
```

**Comment by agin719** [comment]
1、os.Getenv是获取环境变量，请检查下传入的secretid和secretkey，这边看你传入的是空值。
2、presignedURL打印请用fmt.Println(presignedURL.String())，你这样打印末尾会多一个%符号。

**Comment by virskor** [comment]
os.Getenv 在我实际的运行中，我使用的是 "" 对应我的skid skkey，因为这是敏感信息所以我没有post伤害

问题在于
```go

// GetPresignedURL get the object presigned to down or upload file by url
func (s *ObjectService) GetPresignedURL(ctx context.Context, httpMethod, name, ak, sk string, expired time.Duration, opt interface{}) (*url.URL, error) {
	sendOpt := sendOptions{
		baseURL:   s.client.BaseURL.BucketURL,
		uri:       "/" + encodeURIComponent(name),
		method:    httpMethod,
		optQuery:  opt,
		optHeader: opt,
	}
	req, err := s.client.newRequest(ctx, sendOpt.baseURL, sendOpt.uri, sendOpt.method, sendOpt.body, sendOpt.optQuery, sendOpt.optHeader)
	if err != nil {
		return nil, err
	}
```

encodeURIComponent这个 为什么要 这样处理name，如果name带路径，返回的签名后的地址就错了，没有办法访问，而其他语言的sdk似乎没有这个问题

**Comment by virskor** [comment]
因为name 被转为了 /public%2Favatar%2F000%2F00%2F00%2F01.png 这就没有办法访问了

**Comment by agin719** [comment]
跟这个没关系哈，我这边测试都没这个问题，因为可能涉及敏感数据，方便的话，请在腾讯云上提个单工。

**Comment by virskor** [comment]
嗯

**Comment by virskor** [comment]
好的，谢谢

**Comment by gueinhe** [comment]
同样遇到这个问题
