### ISSUE TITLE
Object的上传接口不再支持reader

### ISSUE THREAD

**Issue by wanyhamo** [tencentyun/cos-go-sdk-v5#114]
这个功能是非常好用的，现在封装的上传接口只能传入文件名，感觉是舍本逐末的行为，希望能恢复原来的支持reader处理

**Comment by agin719** [comment]
您好，请问您指的是哪个接口，上传接口一直都支持以reader的方式上传的。
https://cloud.tencent.com/document/product/436/35057#.E7.AE.80.E5.8D.95.E4.B8.8A.E4.BC.A0.E5.AF.B9.E8.B1.A1

**Comment by wanyhamo** [comment]
> 您好，请问您指的是哪个接口，上传接口一直都支持以reader的方式上传的。
> https://cloud.tencent.com/document/product/436/35057#.E7.AE.80.E5.8D.95.E4.B8.8A.E4.BC.A0.E5.AF.B9.E8.B1.A1

超过5G的文件上传需要使用的MultiUpload接口，在19年的版本参数用的是reader现在的参数用的是filepath

**Comment by agin719** [comment]
当前不支持，upload接口使用分块上传时，因为分块上传接口不支持chunk上传，意味着需要先读取输入流并计算长度，在并发较多的情况下，对内存消耗较大。
