### ISSUE TITLE
能不能把tags 用户标签也添加上

### ISSUE THREAD

**Issue by wjcgo** [tencentyun/cos-go-sdk-v5#115]
能不能把tags 用户标签也添加上，感觉使用的是阉割版本，也无需要啊，大哥，好歹也是官方sdk

**Comment by agin719** [comment]
是指object tagging吗？https://github.com/tencentyun/cos-go-sdk-v5/blob/master/example/object/tagging.go

**Comment by wjcgo** [comment]
谢谢，你发给我的object tagging 操作例子地址，对我很有用，但是我确实还没找到上传的时候附加tags参数的方法，先上传再添加tagging,感觉不是很好。

**Comment by agin719** [comment]
目前上传对象还没有单独给tagging添加指定的参数，但是在上传对象时，提供了可选参数XOptionHeader，可以任意添加自定义header，也可以用于添加tagging。

**Comment by wjcgo** [comment]
非常感谢，我一直查找单独参数，没有注意到XOptionHeader。
