### ISSUE TITLE
panic when empty ObjectPutOptions

### ISSUE THREAD

**Issue by pavlelee** [tencentyun/cos-go-sdk-v5#118]
![image](https://user-images.githubusercontent.com/5382358/113867270-e9729080-97e0-11eb-86f6-e2492aae5e8b.png)

https://github.com/tencentyun/cos-go-sdk-v5/blob/v0.7.21/object.go#L189

pointer inline struct must assert self struct not equal nil

**Comment by pavlelee** [comment]
fix pr https://github.com/tencentyun/cos-go-sdk-v5/pull/119

**Comment by agin719** [comment]
Thanks you for your pr, but it has already fixed in latest version. The func cloneObjectPutOptions has ensured that ObjectPutHeaderOptions is not nil.

**Comment by pavlelee** [comment]
Already fix in https://github.com/tencentyun/cos-go-sdk-v5/blob/v0.7.23/object.go，close pr
