### ISSUE TITLE
上传文件名的字符转义问题

### ISSUE THREAD

**Issue by AnastagiZeno** [tencentyun/cos-go-sdk-v5#122]
如果文件名中带有‘/’, 上传的时候会被强制转义，导致上传失败，接口403，

![image](https://user-images.githubusercontent.com/34497871/116379994-23fea480-a846-11eb-8bfc-a99874cd6ac7.png)

**Comment by agin719** [comment]
url编码不会导致403哈，403是权限问题，请查看secretid和secretkey是否正常，且用户是否具有相关权限，如果还有问题，可以提交工单咨询。
