### ISSUE TITLE
go get 报错：unknown revision v3.0.233

### ISSUE THREAD

**Issue by iyangyi** [tencentyun/cos-go-sdk-v5#138]
$ go get -u github.com/tencentyun/cos-go-sdk-v5
go get: github.com/tencentyun/cos-go-sdk-v5@v0.7.25 updating to
        github.com/tencentyun/cos-go-sdk-v5@v0.7.26 requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.233+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.233: unknown revision v3.0.233

**Comment by agin719** [comment]
麻烦再尝试下呢？
