### ISSUE TITLE
v0.7.26 checksum mismatch

### ISSUE THREAD

**Issue by Xuanwo** [tencentyun/cos-go-sdk-v5#140]
Our CI failed for this error: https://github.com/beyondstorage/go-service-cos/pull/33

```shell
verifying github.com/tencentyun/cos-go-sdk-v5@v0.7.26/go.mod: checksum mismatch
	downloaded: h1:O5LmgDLDk6mAsFLhQ2L/BNiJJDQIXE+mYFs2UiUMLaI=
	go.sum:     h1:4E4+bQ2gBVJcgEC9Cufwylio4mXOct2iu05WjgEBx1o=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [Makefile:38: tidy] Error 1
```

**Comment by agin719** [comment]
please try again?

**Comment by Xuanwo** [comment]
Still fail after retry: https://github.com/beyondstorage/go-service-cos/pull/33/checks?check_run_id=2912346980

**Comment by Xuanwo** [comment]
Maybe we should not update tags after they have been published. How about bump a new version to resolve this?

**Comment by agin719** [comment]
I have bumped a version, please try again?

**Comment by Xuanwo** [comment]
Let's wait for dependabot's next update.

**Comment by Xuanwo** [comment]
It works, thanks for the quick response.
