### ISSUE TITLE
Request for adding old version tags

### ISSUE THREAD

**Issue by HeroSizy** [tencentyun/cos-go-sdk-v5#147]
We are developing on a old code base and it depends on version v0.7.0, and it is not compatible with the latest version v0.7.30 because of unmatched variable type.

But this version cannot be found in this repo anymore 

```bash
go get: github.com/tencentyun/cos-go-sdk-v5@v0.7.0: invalid version: unknown revision v0.7.0
```

can you add the tag back?

**Comment by agin719** [comment]
This git doesn't have tag of v0.7.0, and I don't know which commit the tag v0.7.0 point to.  I suggest you upgrade your dependency library.
