### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by jingc1413** [tencentyun/cos-go-sdk-v5#163]
sdk version: v0.7.25
put object, 偶而会出现, write tcp 172.18.x.x -> 121.4.234.x:443 use of closed network connection 
这种情况, 怎么处理, 只能业务逻辑重试 再次put 吗?

**Comment by agin719** [comment]
是的，也可以尝试把 Transport.MaxIdleConnsPerHost 和 Transport.MaxIdleConns 调大
