### ISSUE TITLE
高级接口 能不能提供一个 io.Reader

### ISSUE THREAD

**Issue by langlang777** [tencentyun/cos-go-sdk-v5#166]
func (s *ObjectService) Upload(ctx context.Context, key string, filepath string, opt *MultiUploadOptions) 

只能传 filepath 很不方便啊

**Comment by HammerMax** [comment]
+1

**Comment by lostpg** [comment]
@agin719 麻烦看一下这个issue，go 和 java sdk的upload接口都要传file或filepath，这个做法个人也认为不如使用字节流做参数方便和安全。

**Comment by agin719** [comment]
目前还不支持，upload接口使用分块上传时，因为分块上传接口不支持chunk上传，意味着需要先读取输入流并计算长度，在并发较多的情况下，对内存消耗较大。
