### ISSUE TITLE
The path in the *url.URL returned by GetPresignedURL begins with 2 "/" when param name begin with "/"

### ISSUE THREAD

**Issue by shenhaofang** [tencentyun/cos-go-sdk-v5#174]
The path in the *url.URL returned by GetPresignedURL begins with 2 "/" when param name begin with "/"
I saw the code in object.go
https://github.com/tencentyun/cos-go-sdk-v5/blob/798afa3c76520ba28c20a5d36daf8b48d78a27c1/object.go#L127

I think the if condition is wrong, an "!" should be added before the condition

**Comment by agin719** [comment]
key = "/file" is different from key = "file". the key passed by users is consistent in GetPresignedURL
