### ISSUE TITLE
我能在 newclient 之后再设置 bucketurl么  看了下api 没找到合适的  或者说有没有灵活点的，不然每次不同的bucket都需要从新new一次

### ISSUE THREAD

**Issue by zxjzzz** [tencentyun/cos-go-sdk-v5#177]
![97fca99e5dadd7c48150aa82cb12ab6](https://user-images.githubusercontent.com/34086787/195295004-6a11f356-09c2-4459-aabf-c33406b672c2.jpg)
https://cloud.tencent.com/document/product/436/65644#.E4.B8.8A.E4.BC.A0.E5.AF.B9.E8.B1.A1

**Comment by agin719** [comment]
可以直接设置client.BaseURL，但不保证并发安全，建议每个桶新建一个client
