### ISSUE TITLE
GetBucket或者GetBucketACL应该返回ACL

### ISSUE THREAD

**Issue by hiscal2015** [tencentyun/cos-go-sdk-v5#18]
Hi, 

PutBucket/PutBucketACL均支持ACL参数（存储桶公共权限），但是GetBucket/GetBucketACL的响应体里面并没有返回ACL，作为存储桶的一个重要参数，可否添加到响应体里面去？谢谢。

**Comment by toranger** [comment]
GetBucketACL 会返回对应的ACL结构，默认是私有，如果有其他设置，在URI为http://cam.qcloud.com/groups/global/AllUsers下有对应的授权。返回内容上都是根据标准API走的恩
