### ISSUE TITLE
rand.Seed 只需要在init中设置一次

### ISSUE THREAD

**Issue by hanjm** [tencentyun/cos-go-sdk-v5#180]
https://github.com/tencentyun/cos-go-sdk-v5/blob/0f7612855ca6c4c5a8b173f7a4d1bfbe267a6067/auth.go#L62-L64

https://stackoverflow.com/questions/12321133/how-to-properly-seed-random-number-generator

**Comment by agin719** [comment]
多谢，已更新
https://github.com/tencentyun/cos-go-sdk-v5/commit/6003c8dafec3f1703d0f900a009e695bee7addf6
