### ISSUE TITLE
上传文件时如何添加自定义header?

### ISSUE THREAD

**Issue by virskor** [tencentyun/cos-go-sdk-v5#196]
数据持久化处理中，长传文件时object..put如何添加Pic-Operations到header中？

```plaintext
{"is_pic_info":0,"rules":[{"fileid":"/uploads/1/d6172f8401bd5cb14828d55d4d06fd31.jpeg","rule":"imageMogr2/rquality/70/strip|watermark/1/image/aHR0cDovL3lpbmdjdWktY24tcHJvZC0xMjU3NjU4Nzc5LmNvcy5hcC1iZWlqaW5nLm15cWNsb3VkLmNvbS9pbWFnZXMvd2F0ZXJtYXJrX2NvbG9yLnBuZw/dissolve/100/dx/20/dy/20/gravity/southeast/scatype/3/spcent/49|watermark/3/type/3/text/eWluZ2N1aWNu"}]}
```

**Comment by virskor** [comment]
https://github.com/tencentyun/qcloud-documents/blob/master/product/%E5%9B%BE%E7%89%87%E6%9C%8D%E5%8A%A1/%E5%9B%BE%E7%89%87%E5%A4%84%E7%90%86/API%20%E6%96%87%E6%A1%A3/%E6%8C%81%E4%B9%85%E5%8C%96%E5%A4%84%E7%90%86.md


上传时处理

**Comment by virskor** [comment]
any reply????????

**Comment by agin719** [comment]
https://cloud.tencent.com/document/product/436/55365
