### ISSUE TITLE
上传本地文件夹问题 

### ISSUE THREAD

**Issue by zxianx** [tencentyun/cos-go-sdk-v5#214]
问题1：未找到上传文件夹的方法，目前是通过walk遍历上传，有无更好方法

问题2：如何上传一个空文件夹

**Comment by zxianx** [comment]
问题2已解决，上传 object.put 一个空对象即可。 eg    .Object.Put(ctx,“test/dir1/”, nil, nil)

**Comment by agin719** [comment]
上传文件夹目前需要业务遍历文件夹来上传。
