### ISSUE TITLE
高级分块上传支持自定义分块上传worker

### ISSUE THREAD

**Issue by unihon** [tencentyun/cos-go-sdk-v5#219]
高级分块上传支持自定义分块上传worker.

在大文件上传时需要耗费大量时间，有些场景需要在不同时刻采用不同的上传速率、暂停上传。
希望高级分块上传支持自定义的分块上传worker

**Comment by agin719** [comment]
这种建议用户直接通过分块上传接口来定制符合业务的上传方式。
