### ISSUE TITLE
您好，ACL用到的一些的字面值常量是否可以做成枚举值呢？或者加一些内置的常量这样外部调用时可以引用？

### ISSUE THREAD

**Issue by CC11001100** [tencentyun/cos-go-sdk-v5#231]
比如这个API代码示例：

[https://github.com/tencentyun/cos-go-sdk-v5/blob/master/example/object/putACL.go](https://github.com/tencentyun/cos-go-sdk-v5/blob/master/example/object/putACL.go)

在设置`XCosACL`的时候是直接使用的字面值常量，不是很方便记忆，同时还可能打错：

```go
	opt := &cos.ObjectPutACLOptions{
		Header: &cos.ACLHeaderOptions{
			XCosACL: "private",
		},
	}
```

我查阅了COS的ACL文档：

[https://cloud.tencent.com/document/product/436/30752](https://cloud.tencent.com/document/product/436/30752)

其中【预设的 ACL】部分提到了一些预设的权限：

![image](https://github.com/tencentyun/cos-go-sdk-v5/assets/12819457/f6f63245-a087-4699-828d-68d043089f4d)

既然如此为什么不在SDK内加一些常量以方便引用这些预设ACL呢，这样就不需要记忆了，使用起来有代码提示，又不用担心打错字导致调用出错，如果您觉得可以但是又不想自己加，我可以提一个pr

**Comment by agin719** [comment]
感谢建议，后续版本会加上
