### ISSUE TITLE
使用c.Object.Upload上传10G大文件，网络条件不好时，过了3个小时会报Your socket connection to the server was not read from or written to within the timeout period,设置了http.client,timeout为60秒依然存在这个问题

### ISSUE THREAD

**Issue by AnderFengYu** [tencentyun/cos-go-sdk-v5#237]
使用c.Object.Upload上传10G大文件，每个分片数是16M,poolsize为25，网络条件不好时，过了3个小时会报Your socket connection to the server was not read from or written to within the timeout period,设置了http.client,timeout为60秒依然存在这个问题

**Comment by agin719** [comment]
没见您回复，这里先把问题关闭了，如果还有其他疑问可以重新打开，或者直接提工单到腾讯云官网。
