### ISSUE TITLE
DocPreviewHTMLOptions 少了 weboffice_url 和 tokenuid 参数

### ISSUE THREAD

**Issue by kasuganosora** [tencentyun/cos-go-sdk-v5#238]
https://github.com/tencentyun/cos-go-sdk-v5/blob/2f05c9814f68f14af9edc3e124286348709d5496/ci_doc.go#L345

具体 文档说明 https://cloud.tencent.com/document/product/460/59410

**Comment by agin719** [comment]
[e30dc658a3defb53fcf023d526c274b08db4532e](https://github.com/tencentyun/cos-go-sdk-v5/commit/e30dc658a3defb53fcf023d526c274b08db4532e)
已添加
