### ISSUE TITLE
是否可以支持sts认证

### ISSUE THREAD

**Issue by ioito** [tencentyun/cos-go-sdk-v5#253]
采取 https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/role_arn_provider.go 认证

**Comment by ioito** [comment]
@agin719

**Comment by agin719** [comment]
sts可使用以下库：
1、https://github.com/TencentCloud/tencentcloud-sdk-go
2、https://github.com/tencentyun/qcloud-cos-sts-sdk/tree/master/go

**Comment by ioito** [comment]
https://github.com/tencentyun/cos-go-sdk-v5/blob/bd0557e60c3a0de768996d5ad6d3ac78db581730/auth.go#L460-L475
能不能直接集成到此仓库，类似如上，能自动刷新秘钥

**Comment by agin719** [comment]
建议提个需求单到腾讯云，后续可以排期支持。

**Comment by ioito** [comment]
是提到这里么: https://cloud.tencent.com/voc/tasks/12568
还是其他地方

**Comment by agin719** [comment]
已转需求单，这里先关闭
