### ISSUE TITLE
CredentialIface does not implement "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface (missing method GetCredential)

### ISSUE THREAD

**Issue by wangstrider** [tencentyun/cos-go-sdk-v5#263]
variable of type "github.com/tencentyun/cos-go-sdk-v5".CredentialIface) as "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface value in argument to sts.NewClient: "github.com/tencentyun/cos-go-sdk-v5".CredentialIface does not implement "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface (missing method GetCredential)

github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.950

**Comment by agin719** [comment]
There are no relationship between github.com/tencentyun/cos-go-sdk-v5".CredentialIface 
 and github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface.
