### ISSUE TITLE
FileProcessJobsDetail 漏掉了 Progress 字段

### ISSUE THREAD

**Issue by kasuganosora** [tencentyun/cos-go-sdk-v5#272]
type FileProcessJobsDetail struct {
	Code         string                   `xml:",omitempty"`
	Message      string                   `xml:",omitempty"`
	JobId        string                   `xml:",omitempty"`
	Tag          string                   `xml:",omitempty"`
	State        string                   `xml:",omitempty"`
	CreationTime string                   `xml:",omitempty"`
	StartTime    string                   `xml:",omitempty"`
	EndTime      string                   `xml:",omitempty"`
	QueueId      string                   `xml:",omitempty"`
	Input        *FileProcessInput        `xml:",omitempty"`
	Operation    *FileProcessJobOperation `xml:",omitempty"`
}

对应文档 https://cloud.tencent.com/document/product/436/83111

**Comment by eust-w** [comment]
直接改了提个pr吧

**Comment by agin719** [comment]
https://github.com/tencentyun/cos-go-sdk-v5/commit/9aa25ecc4d7e7b8f3828a402990c81d554773ccb 已支持
