### ISSUE TITLE
example bug

### ISSUE THREAD

**Issue by ZYNCMA** [tencentyun/cos-go-sdk-v5#36]
https://github.com/tencentyun/cos-go-sdk-v5/blob/68aae1f806e149b0818763e2e5ff96858e914511/example/object/get.go#L58

https://github.com/tencentyun/cos-go-sdk-v5/blob/68aae1f806e149b0818763e2e5ff96858e914511/object.go#L63

`c.Object.GetToFile` returns 2 values while the example assigns 1 variable only.

**Comment by toranger** [comment]
Thanks for feedback, I will fix it.

**Comment by toranger** [comment]
[#48 ](https://github.com/tencentyun/cos-go-sdk-v5/pull/48)  merge fixed
