### ISSUE TITLE
内网的时候x509有办法吗

### ISSUE THREAD

**Issue by hyacinthus** [tencentyun/cos-go-sdk-v5#7]
在内网的时候，cos会解析到内部地址，然后ca证书就有问题了
golang就会报

x509: certificate signed by unknown authority

https://github.com/mozillazg/go-cos/issues/8

**Comment by toranger** [comment]
这里是怎么配置的呢，我拿内网环境试了下是可以的
![image](https://user-images.githubusercontent.com/23206440/50089328-8855d600-0240-11e9-8722-4381188167f9.png)

**Comment by toranger** [comment]
这里是怎么配置的呢，我拿内网环境试了下是可以的
![_20181217211220](https://user-images.githubusercontent.com/23206440/50089416-bfc48280-0240-11e9-9ac8-95480d127c09.png)

**Comment by hyacinthus** [comment]
@tomleader 
我用你这个demo，做了个镜像。
https://github.com/hyacinthus/cos-go-sdk-v5/blob/master/example/object/Dockerfile
代码和镜像都在这里

下边是运行时的截图

```sh
➜  xbswarm git:(master) ✗ sh test.sh
Unable to find image 'hub.tencentyun.com/muninn/costest:latest' locally
latest: Pulling from muninn/costest
54f7e8ac135a: Already exists 
06be90607741: Pull complete 
Digest: sha256:07ff03fd79892259f3d65597bf0107dc840e2d98bd8dba3b2111d3acdf12ab4e
Status: Downloaded newer image for hub.tencentyun.com/muninn/costest:latest
GET /test.txt HTTP/1.1
Host: static-1256176061.cos.ap-shanghai.myqcloud.com
User-Agent: cos-go-sdk-v5/0.7.3
Authorization: q-sign-algorithm=sha1&q-ak=AKIDa4LUTIXaIsJaigESGMI71oQ0UrMhr9qU&q-sign-time=1545062023;1545065623&q-key-time=1545062023;1545065623&q-header-list=content-type&q-url-param-list=&q-signature=8adcf7ba37d5373221309cf205c27631b4f03b66
Content-Type: application/xml
Accept-Encoding: gzip



panic: Get https://static-1256176061.cos.ap-shanghai.myqcloud.com/test.txt: x509: certificate signed by unknown authority

goroutine 1 [running]:
main.main()
	/app/get.go:36 +0x7c8
```

大家用golang一般都是在docker里的，我在服务器上还真没装golang环境，也没法直接试验。

**Comment by toranger** [comment]
嗯，那可以先排除下是否是docker环境的因素，在内网装个go的amd包跑程序试下，明天我也试下docker环境的

**Comment by hyacinthus** [comment]
不好意思，经过这么一对比，刚又琢磨了一会，想起来我遇到过的这个坑。
虽然走的内网但是cvm是能连外网的，应该是能验证签名的呀。
于是想起来 debian 的裸镜像是没预装证书的。
需要在 dockerfile 里自己装 ca-certificates 这个包。

```Dockerfile
...
FROM debian

RUN apt-get update \
    && apt-get install -y -q --no-install-recommends \
    ca-certificates \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/*

ENV TZ=Asia/Shanghai

COPY --from=build-env /app/app /usr/bin/app

CMD ["app"]
```

ps. 一不小心忘记隐藏ak了，只能重新生成一个。。。
