### ISSUE TITLE
应该做一个判断错误是否为key不存在的函数

### ISSUE THREAD

**Issue by hyacinthus** [tencentyun/cos-go-sdk-v5#70]
类似于这样的

https://pkg.go.dev/github.com/jinzhu/gorm?tab=doc#IsRecordNotFoundError

可以在错误里把 key 不存在分拣出来

if IsNoSuchKeyError(err) {
    ...
} else if err != nil {
    return nil,err
}

**Comment by agin719** [comment]
感谢反馈，后续我们会考虑加上这个接口的，对于需要判断key不存在情况，目前可以判断返回的Response.StatusCode是否为404.
resp, err := c.Object.Get(context.Background(), name, nil)
if resp.StatusCode == 404 {
} else if err != nil {
}

**Comment by hyacinthus** [comment]
嗯，主要我看官网上 404 有很多种情况，只挑出 NoSuchKey 那种情况比较科学，其他情况还真是错误。
