### ISSUE TITLE
怎么设置代理呢

### ISSUE THREAD

**Issue by wg2019** [tencentyun/cos-go-sdk-v5#71]
服务器访问不了外网，想通过代理的方式请求cos，我看java是有sdk的，go没有找到

**Comment by agin719** [comment]
默认通过环境变量http_proxy 和 https_proxy实现代理，或者在代码里面设置http.Transport实现代理。
    proxy := func(_ *http.Request) (*url.URL, error) {
        return url.Parse("http://ip:port")
    }
    c := cos.NewClient(b, &http.Client{
        Transport: &cos.AuthorizationTransport{
            SecretID:  os.Getenv("COS_SECRETID"),
            SecretKey: os.Getenv("COS_SECRETKEY"),
            Transport: &http.Transport{
                 Proxy: proxy,
                 DialContext: (&net.Dialer{
                     Timeout:   30 * time.Second,
                     KeepAlive: 30 * time.Second,
                    DualStack: true,
                 }).DialContext,
                 MaxIdleConns:          100, 
                 IdleConnTimeout:       90 * time.Second,
                 TLSHandshakeTimeout:   10 * time.Second,
                 ExpectContinueTimeout: 1 * time.Second,            
           },  
        },  
    })

**Comment by wg2019** [comment]
谢啦
