### ISSUE TITLE
版本升级报签名错误

### ISSUE THREAD

**Issue by cjieyan** [tencentyun/cos-go-sdk-v5#88]
从
github.com/tencentyun/cos-go-sdk-v5 v0.7.7
升级到
github.com/tencentyun/cos-go-sdk-v5 v0.7.9
报签名错误:
403 SignatureDoesNotMatch(Message: The Signature you specified is invalid.,

**Comment by agin719** [comment]
麻烦提供下request id

**Comment by cjieyan** [comment]
> 麻烦提供下request id

SignatureDoesNotMatch(Message: The Signature you specified is invalid., RequestId: NWY3MDg2ZGRfMThiMjk0MGFfNjQzNF8xMTAwNTMz, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=)

**Comment by agin719** [comment]
> > 麻烦提供下request id
> 
> SignatureDoesNotMatch(Message: The Signature you specified is invalid., RequestId: NWY3MDg2ZGRfMThiMjk0MGFfNjQzNF8xMTAwNTMz, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=)

请检查下secretid和secretkey是否正确，如果还未得到解决，可移步到https://console.cloud.tencent.com/workorder/category提交工单。

**Comment by agin719** [comment]
> > 麻烦提供下request id
> 
> SignatureDoesNotMatch(Message: The Signature you specified is invalid., RequestId: NWY3MDg2ZGRfMThiMjk0MGFfNjQzNF8xMTAwNTMz, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=)

请检查下secretid和secretkey是否正确，如果还未得到解决，可移步到 https://console.cloud.tencent.com/workorder/category 提交工单。

**Comment by cjieyan** [comment]
> > > 麻烦提供下request id
> > 
> > 
> > SignatureDoesNotMatch(Message: The Signature you specified is invalid., RequestId: NWY3MDg2ZGRfMThiMjk0MGFfNjQzNF8xMTAwNTMz, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=)
> 
> 请检查下secretid和secretkey是否正确，如果还未得到解决，可移步到 https://console.cloud.tencent.com/workorder/category 提交工单。

业务代码一行没改.....
secretid和secretkey v0.7.7和v0.7.9版本使用的是一致的,你们底层的类库没自测过么........

**Comment by agin719** [comment]
> > > > 麻烦提供下request id
> > > 
> > > 
> > > SignatureDoesNotMatch(Message: The Signature you specified is invalid., RequestId: NWY3MDg2ZGRfMThiMjk0MGFfNjQzNF8xMTAwNTMz, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=)
> > 
> > 
> > 请检查下secretid和secretkey是否正确，如果还未得到解决，可移步到 https://console.cloud.tencent.com/workorder/category 提交工单。
> 
> 业务代码一行没改.....
> secretid和secretkey v0.7.7和v0.7.9版本使用的是一致的,你们底层的类库没自测过么........

做过测试确认没问题才会发布的。
