### ISSUE TITLE
UploadPart 这个接口不支持传 Content-MD5

### ISSUE THREAD

**Issue by xcaptain** [tencentyun/cos-go-sdk-v5#97]
按照 [https://cloud.tencent.com/document/product/436/36427](https://cloud.tencent.com/document/product/436/36427) 的说法，在进行分块上传时，应该要能自定义 `x-cos-meta-md5` 这个头，但是目前`UploadPart`不支持，想问下有什么办法解决吗

**Comment by agin719** [comment]
最新的版本已支持

**Comment by xcaptain** [comment]
确认可以了
